//! Every selector a census of one AppKit application (its own code and
//! the libraries it links) found it sending, and found present in
//! Sidestep, sent `respondsToSelector:` on a real instance of the class
//! (or the class, for class methods): a straggler that went missing, or
//! a class cluster whose concrete class lacks one its public class has,
//! answers NO. Classes this file has no way to make are asked with
//! `instancesRespondToSelector:`. A debug-build test (release builds
//! skip it); on macOS it checks the list against AppKit itself.
//!
//! Protocol methods are asked of an AppKit class that adopts the
//! protocol (NSView for NSAccessibility, NSTextView for the key binding
//! commands and NSTextInputClient). Initializers are asked of the class
//! (`instancesRespondToSelector:`), as they belong to allocated objects.

use std::ffi::CString;

use objc2::rc::{Allocated, Retained};
use objc2::runtime::{AnyClass, AnyObject, Sel};
use objc2::{AnyThread, MainThreadMarker, msg_send};
use objc2_app_kit::{
    NSApplication, NSApplicationActivationPolicy, NSBackingStoreType, NSColor, NSEvent, NSEventModifierFlags,
    NSEventType, NSFont, NSImage, NSWindowStyleMask,
};
use objc2_foundation::{NSPoint, NSRange, NSRect, NSSize, NSString, NSURL, NSValue};

use sidestep as _;

/// (class method, class, selector).
const SENT: &[(bool, &str, &str)] = &[
    (false, "CAAnimation", "setTimingFunction:"),
    (true, "CAAnimation", "animation"),
    (false, "CAAnimationGroup", "setAnimations:"),
    (true, "CAAnimationGroup", "animation"),
    (false, "CABasicAnimation", "beginTime"),
    (false, "CABasicAnimation", "fillMode"),
    (false, "CABasicAnimation", "setAutoreverses:"),
    (false, "CABasicAnimation", "setBeginTime:"),
    (false, "CABasicAnimation", "setDuration:"),
    (false, "CABasicAnimation", "setFillMode:"),
    (false, "CABasicAnimation", "setFromValue:"),
    (false, "CABasicAnimation", "setRepeatCount:"),
    (false, "CABasicAnimation", "setToValue:"),
    (true, "CABasicAnimation", "animationWithKeyPath:"),
    (false, "CADisplayLink", "addToRunLoop:forMode:"),
    (false, "CADisplayLink", "invalidate"),
    (false, "CAKeyframeAnimation", "keyTimes"),
    (false, "CAKeyframeAnimation", "setKeyTimes:"),
    (false, "CAKeyframeAnimation", "setTimingFunctions:"),
    (false, "CAKeyframeAnimation", "setValues:"),
    (false, "CAKeyframeAnimation", "timingFunctions"),
    (true, "CAKeyframeAnimation", "animationWithKeyPath:"),
    (false, "CALayer", "addAnimation:forKey:"),
    (false, "CALayer", "addSublayer:"),
    (false, "CALayer", "backgroundColor"),
    (false, "CALayer", "bounds"),
    (false, "CALayer", "contentsAreFlipped"),
    (false, "CALayer", "presentationLayer"),
    (false, "CALayer", "removeAllAnimations"),
    (false, "CALayer", "removeAnimationForKey:"),
    (false, "CALayer", "renderInContext:"),
    (false, "CALayer", "setBackgroundColor:"),
    (false, "CALayer", "setBorderColor:"),
    (false, "CALayer", "setBorderWidth:"),
    (false, "CALayer", "setContents:"),
    (false, "CALayer", "setCornerCurve:"),
    (false, "CALayer", "setCornerRadius:"),
    (false, "CALayer", "setFrame:"),
    (false, "CALayer", "setHidden:"),
    (false, "CALayer", "setMaskedCorners:"),
    (false, "CALayer", "setMasksToBounds:"),
    (false, "CALayer", "setNeedsDisplay"),
    (false, "CALayer", "setNeedsDisplayInRect:"),
    (false, "CALayer", "setOpacity:"),
    (false, "CALayer", "setShadowColor:"),
    (false, "CALayer", "setShadowOffset:"),
    (false, "CALayer", "setShadowOpacity:"),
    (false, "CALayer", "setShadowRadius:"),
    (false, "CALayer", "sublayers"),
    (true, "CALayer", "layer"),
    (true, "CALayer", "new"),
    (true, "CAMediaTimingFunction", "functionWithControlPoints::::"),
    (true, "CAMediaTimingFunction", "functionWithName:"),
    (false, "CASpringAnimation", "setDamping:"),
    (false, "CASpringAnimation", "setMass:"),
    (false, "CASpringAnimation", "setStiffness:"),
    (false, "CASpringAnimation", "settlingDuration"),
    (true, "CASpringAnimation", "animationWithKeyPath:"),
    (true, "CATransaction", "begin"),
    (true, "CATransaction", "commit"),
    (true, "CATransaction", "flush"),
    (true, "CATransaction", "setDisableActions:"),
    (false, "CATransition", "setSubtype:"),
    (false, "CATransition", "setType:"),
    (true, "CATransition", "new"),
    (false, "NSAlert", "addButtonWithTitle:"),
    (false, "NSAlert", "runModal"),
    (false, "NSAlert", "setAccessoryView:"),
    (false, "NSAlert", "setAlertStyle:"),
    (false, "NSAlert", "setInformativeText:"),
    (false, "NSAlert", "setMessageText:"),
    (false, "NSAlert", "window"),
    (true, "NSAlert", "new"),
    (false, "NSAnimationContext", "setAllowsImplicitAnimation:"),
    (false, "NSAnimationContext", "setDuration:"),
    (false, "NSAnimationContext", "setTimingFunction:"),
    (true, "NSAnimationContext", "runAnimationGroup:"),
    (true, "NSAnimationContext", "runAnimationGroup:completionHandler:"),
    (false, "NSAppearance", "bestMatchFromAppearancesWithNames:"),
    (false, "NSAppearance", "performAsCurrentDrawingAppearance:"),
    (true, "NSAppearance", "appearanceNamed:"),
    (true, "NSAppearance", "currentDrawingAppearance"),
    (false, "NSApplication", "activateIgnoringOtherApps:"),
    (false, "NSApplication", "currentEvent"),
    (false, "NSApplication", "delegate"),
    (false, "NSApplication", "effectiveAppearance"),
    (false, "NSApplication", "keyWindow"),
    (false, "NSApplication", "mainMenu"),
    (false, "NSApplication", "replyToApplicationShouldTerminate:"),
    (false, "NSApplication", "run"),
    (false, "NSApplication", "sendAction:to:from:"),
    (false, "NSApplication", "sendEvent:"),
    (false, "NSApplication", "setActivationPolicy:"),
    (false, "NSApplication", "setAppearance:"),
    (false, "NSApplication", "setDelegate:"),
    (false, "NSApplication", "setMainMenu:"),
    (false, "NSApplication", "terminate:"),
    (false, "NSApplication", "windows"),
    (true, "NSApplication", "sharedApplication"),
    (false, "NSArray", "containsObject:"),
    (false, "NSArray", "count"),
    (false, "NSArray", "firstObject"),
    (false, "NSArray", "getObjects:"),
    (false, "NSArray", "initWithObjects:count:"),
    (false, "NSArray", "objectAtIndex:"),
    (true, "NSArray", "new"),
    (false, "NSAttributedString", "attribute:atIndex:effectiveRange:"),
    (false, "NSAttributedString", "attribute:atIndex:longestEffectiveRange:inRange:"),
    (false, "NSAttributedString", "attributedSubstringFromRange:"),
    (false, "NSAttributedString", "attributesAtIndex:effectiveRange:"),
    (false, "NSAttributedString", "enumerateAttribute:inRange:options:usingBlock:"),
    (false, "NSAttributedString", "enumerateAttributesInRange:options:usingBlock:"),
    (false, "NSAttributedString", "initWithString:"),
    (false, "NSAttributedString", "initWithString:attributes:"),
    (false, "NSAttributedString", "isEqualToAttributedString:"),
    (false, "NSAttributedString", "length"),
    (false, "NSAttributedString", "string"),
    (true, "NSAttributedString", "alloc"),
    (true, "NSAttributedString", "new"),
    (false, "NSBezierPath", "appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:"),
    (false, "NSBezierPath", "appendBezierPathWithArcWithCenter:radius:startAngle:endAngle:clockwise:"),
    (false, "NSBezierPath", "appendBezierPathWithRect:"),
    (false, "NSBezierPath", "closePath"),
    (false, "NSBezierPath", "elementAtIndex:associatedPoints:"),
    (false, "NSBezierPath", "elementCount"),
    (false, "NSBezierPath", "fill"),
    (false, "NSBezierPath", "lineToPoint:"),
    (false, "NSBezierPath", "moveToPoint:"),
    (false, "NSBezierPath", "setLineCapStyle:"),
    (false, "NSBezierPath", "setLineDash:count:phase:"),
    (false, "NSBezierPath", "setLineJoinStyle:"),
    (false, "NSBezierPath", "setLineWidth:"),
    (false, "NSBezierPath", "stroke"),
    (true, "NSBezierPath", "bezierPath"),
    (true, "NSBezierPath", "bezierPathWithOvalInRect:"),
    (true, "NSBezierPath", "bezierPathWithRect:"),
    (true, "NSBezierPath", "bezierPathWithRoundedRect:xRadius:yRadius:"),
    (true, "NSBezierPath", "fillRect:"),
    (true, "NSBezierPath", "new"),
    (false, "NSBitmapImageRep", "bitmapData"),
    (false, "NSBitmapImageRep", "bitmapFormat"),
    (false, "NSBitmapImageRep", "bitsPerPixel"),
    (false, "NSBitmapImageRep", "bytesPerRow"),
    (
        false,
        "NSBitmapImageRep",
        "initWithBitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:",
    ),
    (
        false,
        "NSBitmapImageRep",
        "initWithBitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bytesPerRow:bitsPerPixel:",
    ),
    (false, "NSBitmapImageRep", "isPlanar"),
    (false, "NSBitmapImageRep", "representationUsingType:properties:"),
    (false, "NSBitmapImageRep", "samplesPerPixel"),
    (true, "NSBitmapImageRep", "alloc"),
    (false, "NSBox", "contentView"),
    (false, "NSBox", "initWithFrame:"),
    (false, "NSBox", "setBorderColor:"),
    (false, "NSBox", "setBorderWidth:"),
    (false, "NSBox", "setBoxType:"),
    (false, "NSBox", "setContentViewMargins:"),
    (false, "NSBox", "setCornerRadius:"),
    (false, "NSBox", "setFillColor:"),
    (false, "NSBox", "setTitlePosition:"),
    (true, "NSBox", "alloc"),
    (false, "NSBundle", "resourcePath"),
    (true, "NSBundle", "mainBundle"),
    (false, "NSButton", "initWithFrame:"),
    (false, "NSButton", "mouseDown:"),
    (false, "NSButton", "setAttributedTitle:"),
    (false, "NSButton", "setBezelStyle:"),
    (false, "NSButton", "setBordered:"),
    (false, "NSButton", "setContentTintColor:"),
    (false, "NSButton", "setImage:"),
    (false, "NSButton", "setImagePosition:"),
    (false, "NSButton", "setKeyEquivalent:"),
    (false, "NSButton", "setKeyEquivalentModifierMask:"),
    (false, "NSButton", "setState:"),
    (false, "NSButton", "setTitle:"),
    (false, "NSButton", "setTransparent:"),
    (false, "NSButton", "state"),
    (true, "NSButton", "alloc"),
    (true, "NSButton", "buttonWithImage:target:action:"),
    (true, "NSButton", "buttonWithTitle:target:action:"),
    (true, "NSButton", "checkboxWithTitle:target:action:"),
    (true, "NSButton", "new"),
    (true, "NSButton", "radioButtonWithTitle:target:action:"),
    (false, "NSCell", "cellSizeForBounds:"),
    (false, "NSCell", "setLineBreakMode:"),
    (false, "NSCell", "setScrollable:"),
    (false, "NSCell", "setUsesSingleLineMode:"),
    (false, "NSCell", "setWraps:"),
    (true, "NSCharacterSet", "characterSetWithCharactersInString:"),
    (true, "NSCharacterSet", "newlineCharacterSet"),
    (true, "NSCharacterSet", "whitespaceAndNewlineCharacterSet"),
    (false, "NSClipView", "documentView"),
    (false, "NSClipView", "scrollToPoint:"),
    (false, "NSColor", "alphaComponent"),
    (false, "NSColor", "blendedColorWithFraction:ofColor:"),
    (false, "NSColor", "blueComponent"),
    (false, "NSColor", "brightnessComponent"),
    (false, "NSColor", "colorUsingColorSpace:"),
    (false, "NSColor", "colorWithAlphaComponent:"),
    (false, "NSColor", "getRed:green:blue:alpha:"),
    (false, "NSColor", "greenComponent"),
    (false, "NSColor", "redComponent"),
    (false, "NSColor", "set"),
    (false, "NSColor", "setFill"),
    (false, "NSColor", "setStroke"),
    (true, "NSColor", "blackColor"),
    (true, "NSColor", "blueColor"),
    (true, "NSColor", "clearColor"),
    (true, "NSColor", "colorWithCalibratedRed:green:blue:alpha:"),
    (true, "NSColor", "colorWithName:dynamicProvider:"),
    (true, "NSColor", "colorWithRed:green:blue:alpha:"),
    (true, "NSColor", "colorWithSRGBRed:green:blue:alpha:"),
    (true, "NSColor", "controlAccentColor"),
    (true, "NSColor", "controlBackgroundColor"),
    (true, "NSColor", "labelColor"),
    (true, "NSColor", "linkColor"),
    (true, "NSColor", "quaternaryLabelColor"),
    (true, "NSColor", "quaternarySystemFillColor"),
    (true, "NSColor", "secondaryLabelColor"),
    (true, "NSColor", "selectedTextBackgroundColor"),
    (true, "NSColor", "separatorColor"),
    (true, "NSColor", "systemBlueColor"),
    (true, "NSColor", "systemGrayColor"),
    (true, "NSColor", "systemGreenColor"),
    (true, "NSColor", "systemOrangeColor"),
    (true, "NSColor", "systemPinkColor"),
    (true, "NSColor", "systemPurpleColor"),
    (true, "NSColor", "systemRedColor"),
    (true, "NSColor", "systemTealColor"),
    (true, "NSColor", "systemYellowColor"),
    (true, "NSColor", "tertiaryLabelColor"),
    (true, "NSColor", "tertiarySystemFillColor"),
    (true, "NSColor", "textBackgroundColor"),
    (true, "NSColor", "textColor"),
    (true, "NSColor", "underPageBackgroundColor"),
    (true, "NSColor", "whiteColor"),
    (true, "NSColor", "windowBackgroundColor"),
    (true, "NSColorSpace", "deviceRGBColorSpace"),
    (true, "NSColorSpace", "sRGBColorSpace"),
    (false, "NSControl", "abortEditing"),
    (false, "NSControl", "action"),
    (false, "NSControl", "attributedStringValue"),
    (false, "NSControl", "cell"),
    (false, "NSControl", "currentEditor"),
    (false, "NSControl", "doubleValue"),
    (false, "NSControl", "isEnabled"),
    (false, "NSControl", "performClick:"),
    (false, "NSControl", "sendAction:to:"),
    (false, "NSControl", "setAction:"),
    (false, "NSControl", "setAlignment:"),
    (false, "NSControl", "setAttributedStringValue:"),
    (false, "NSControl", "setContinuous:"),
    (false, "NSControl", "setDoubleValue:"),
    (false, "NSControl", "setEnabled:"),
    (false, "NSControl", "setFont:"),
    (false, "NSControl", "setLineBreakMode:"),
    (false, "NSControl", "setRefusesFirstResponder:"),
    (false, "NSControl", "setStringValue:"),
    (false, "NSControl", "setTag:"),
    (false, "NSControl", "setTarget:"),
    (false, "NSControl", "setUsesSingleLineMode:"),
    (false, "NSControl", "sizeToFit"),
    (false, "NSControl", "stringValue"),
    (false, "NSControl", "tag"),
    (false, "NSControl", "target"),
    (false, "NSCursor", "set"),
    (true, "NSCursor", "IBeamCursor"),
    (true, "NSCursor", "arrowCursor"),
    (true, "NSCursor", "pointingHandCursor"),
    (false, "NSData", "bytes"),
    (false, "NSData", "initWithBytes:length:"),
    (false, "NSData", "length"),
    (true, "NSDate", "date"),
    (true, "NSDate", "dateWithTimeIntervalSince1970:"),
    (true, "NSDate", "dateWithTimeIntervalSinceNow:"),
    (true, "NSDateFormatter", "localizedStringFromDate:dateStyle:timeStyle:"),
    (false, "NSDictionary", "count"),
    (false, "NSDictionary", "getObjects:andKeys:"),
    (false, "NSDictionary", "initWithObjects:forKeys:count:"),
    (false, "NSDictionary", "mutableCopy"),
    (false, "NSDictionary", "objectForKey:"),
    (true, "NSDictionary", "alloc"),
    (true, "NSDictionary", "new"),
    (false, "NSError", "localizedDescription"),
    (false, "NSEvent", "charactersIgnoringModifiers"),
    (false, "NSEvent", "clickCount"),
    (false, "NSEvent", "keyCode"),
    (false, "NSEvent", "locationInWindow"),
    (false, "NSEvent", "magnification"),
    (false, "NSEvent", "modifierFlags"),
    (false, "NSEvent", "phase"),
    (false, "NSEvent", "type"),
    (
        true,
        "NSEvent",
        "keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:",
    ),
    (true, "NSEvent", "pressedMouseButtons"),
    (false, "NSFileManager", "URLsForDirectory:inDomains:"),
    (false, "NSFileManager", "contentsOfDirectoryAtURL:includingPropertiesForKeys:options:error:"),
    (false, "NSFileManager", "createDirectoryAtURL:withIntermediateDirectories:attributes:error:"),
    (true, "NSFileManager", "defaultManager"),
    (false, "NSFont", "ascender"),
    (false, "NSFont", "capHeight"),
    (false, "NSFont", "descender"),
    (false, "NSFont", "familyName"),
    (false, "NSFont", "fontDescriptor"),
    (false, "NSFont", "fontWithSize:"),
    (false, "NSFont", "isFixedPitch"),
    (false, "NSFont", "leading"),
    (false, "NSFont", "pointSize"),
    (false, "NSFont", "xHeight"),
    (true, "NSFont", "boldSystemFontOfSize:"),
    (true, "NSFont", "fontWithDescriptor:size:"),
    (true, "NSFont", "fontWithName:size:"),
    (true, "NSFont", "monospacedDigitSystemFontOfSize:weight:"),
    (true, "NSFont", "monospacedSystemFontOfSize:weight:"),
    (true, "NSFont", "systemFontOfSize:"),
    (true, "NSFont", "systemFontOfSize:weight:"),
    (false, "NSFontDescriptor", "fontDescriptorByAddingAttributes:"),
    (false, "NSFontDescriptor", "fontDescriptorWithDesign:"),
    (false, "NSFontDescriptor", "fontDescriptorWithSymbolicTraits:"),
    (false, "NSFontDescriptor", "objectForKey:"),
    (false, "NSFontDescriptor", "symbolicTraits"),
    (true, "NSFontDescriptor", "fontDescriptorWithFontAttributes:"),
    (false, "NSGraphicsContext", "compositingOperation"),
    (false, "NSGraphicsContext", "flushGraphics"),
    (true, "NSGraphicsContext", "currentContext"),
    (true, "NSGraphicsContext", "graphicsContextWithBitmapImageRep:"),
    (true, "NSGraphicsContext", "setCurrentContext:"),
    (false, "NSImage", "addRepresentation:"),
    (false, "NSImage", "drawInRect:"),
    (false, "NSImage", "drawInRect:fromRect:operation:fraction:"),
    (false, "NSImage", "imageWithSymbolConfiguration:"),
    (false, "NSImage", "initWithData:"),
    (false, "NSImage", "initWithSize:"),
    (false, "NSImage", "lockFocus"),
    (false, "NSImage", "representations"),
    (false, "NSImage", "setTemplate:"),
    (false, "NSImage", "size"),
    (false, "NSImage", "unlockFocus"),
    (true, "NSImage", "alloc"),
    (true, "NSImage", "imageWithSize:flipped:drawingHandler:"),
    (true, "NSImage", "imageWithSystemSymbolName:accessibilityDescription:"),
    (false, "NSImageRep", "bitsPerSample"),
    (false, "NSImageRep", "hasAlpha"),
    (false, "NSImageRep", "pixelsHigh"),
    (false, "NSImageRep", "pixelsWide"),
    (false, "NSImageRep", "setAlpha:"),
    (false, "NSImageRep", "setSize:"),
    (false, "NSImageRep", "size"),
    (true, "NSImageSymbolConfiguration", "configurationWithHierarchicalColor:"),
    (true, "NSImageSymbolConfiguration", "configurationWithPointSize:weight:"),
    (true, "NSIndexSet", "indexSetWithIndex:"),
    (false, "NSLayoutAnchor", "constraintEqualToAnchor:"),
    (false, "NSLayoutAnchor", "constraintEqualToAnchor:constant:"),
    (false, "NSLayoutConstraint", "setConstant:"),
    (true, "NSLayoutConstraint", "activateConstraints:"),
    (false, "NSLayoutManager", "addTextContainer:"),
    (false, "NSLayoutManager", "boundingRectForGlyphRange:inTextContainer:"),
    (false, "NSLayoutManager", "characterRangeForGlyphRange:actualGlyphRange:"),
    (false, "NSLayoutManager", "defaultLineHeightForFont:"),
    (false, "NSLayoutManager", "drawBackgroundForGlyphRange:atPoint:"),
    (false, "NSLayoutManager", "drawGlyphsForGlyphRange:atPoint:"),
    (false, "NSLayoutManager", "ensureLayoutForTextContainer:"),
    (false, "NSLayoutManager", "firstUnlaidCharacterIndex"),
    (false, "NSLayoutManager", "glyphRangeForBoundingRect:inTextContainer:"),
    (false, "NSLayoutManager", "glyphRangeForCharacterRange:actualCharacterRange:"),
    (false, "NSLayoutManager", "hasNonContiguousLayout"),
    (false, "NSLayoutManager", "setAllowsNonContiguousLayout:"),
    (false, "NSLayoutManager", "usedRectForTextContainer:"),
    (true, "NSLayoutManager", "new"),
    (false, "NSMenu", "addItem:"),
    (false, "NSMenu", "addItemWithTitle:action:keyEquivalent:"),
    (false, "NSMenu", "indexOfItem:"),
    (false, "NSMenu", "initWithTitle:"),
    (false, "NSMenu", "itemArray"),
    (false, "NSMenu", "itemAtIndex:"),
    (false, "NSMenu", "itemWithTitle:"),
    (false, "NSMenu", "performActionForItemAtIndex:"),
    (false, "NSMenu", "performKeyEquivalent:"),
    (false, "NSMenu", "popUpMenuPositioningItem:atLocation:inView:"),
    (false, "NSMenu", "setAutoenablesItems:"),
    (false, "NSMenu", "update"),
    (true, "NSMenu", "alloc"),
    (true, "NSMenu", "new"),
    (false, "NSMenuItem", "action"),
    (false, "NSMenuItem", "initWithTitle:action:keyEquivalent:"),
    (false, "NSMenuItem", "isEnabled"),
    (false, "NSMenuItem", "representedObject"),
    (false, "NSMenuItem", "setAction:"),
    (false, "NSMenuItem", "setEnabled:"),
    (false, "NSMenuItem", "setKeyEquivalentModifierMask:"),
    (false, "NSMenuItem", "setRepresentedObject:"),
    (false, "NSMenuItem", "setState:"),
    (false, "NSMenuItem", "setSubmenu:"),
    (false, "NSMenuItem", "setTag:"),
    (false, "NSMenuItem", "setTarget:"),
    (false, "NSMenuItem", "setTitle:"),
    (false, "NSMenuItem", "setToolTip:"),
    (false, "NSMenuItem", "submenu"),
    (false, "NSMenuItem", "tag"),
    (true, "NSMenuItem", "alloc"),
    (true, "NSMenuItem", "new"),
    (true, "NSMenuItem", "separatorItem"),
    (false, "NSMutableAttributedString", "addAttribute:value:range:"),
    (false, "NSMutableAttributedString", "addAttributes:range:"),
    (false, "NSMutableAttributedString", "appendAttributedString:"),
    (false, "NSMutableAttributedString", "beginEditing"),
    (false, "NSMutableAttributedString", "deleteCharactersInRange:"),
    (false, "NSMutableAttributedString", "endEditing"),
    (false, "NSMutableAttributedString", "initWithAttributedString:"),
    (false, "NSMutableAttributedString", "initWithString:"),
    (false, "NSMutableAttributedString", "mutableString"),
    (false, "NSMutableAttributedString", "removeAttribute:range:"),
    (false, "NSMutableAttributedString", "replaceCharactersInRange:withAttributedString:"),
    (false, "NSMutableAttributedString", "replaceCharactersInRange:withString:"),
    (false, "NSMutableAttributedString", "setAttributedString:"),
    (false, "NSMutableAttributedString", "setAttributes:range:"),
    (true, "NSMutableAttributedString", "alloc"),
    (true, "NSMutableAttributedString", "new"),
    (false, "NSMutableDictionary", "removeObjectForKey:"),
    (false, "NSMutableParagraphStyle", "copy"),
    (false, "NSMutableParagraphStyle", "firstLineHeadIndent"),
    (false, "NSMutableParagraphStyle", "setAlignment:"),
    (false, "NSMutableParagraphStyle", "setBaseWritingDirection:"),
    (false, "NSMutableParagraphStyle", "setDefaultTabInterval:"),
    (false, "NSMutableParagraphStyle", "setFirstLineHeadIndent:"),
    (false, "NSMutableParagraphStyle", "setHeadIndent:"),
    (false, "NSMutableParagraphStyle", "setHyphenationFactor:"),
    (false, "NSMutableParagraphStyle", "setLineBreakMode:"),
    (false, "NSMutableParagraphStyle", "setLineHeightMultiple:"),
    (false, "NSMutableParagraphStyle", "setLineSpacing:"),
    (false, "NSMutableParagraphStyle", "setMaximumLineHeight:"),
    (false, "NSMutableParagraphStyle", "setMinimumLineHeight:"),
    (false, "NSMutableParagraphStyle", "setParagraphSpacing:"),
    (false, "NSMutableParagraphStyle", "setParagraphSpacingBefore:"),
    (false, "NSMutableParagraphStyle", "setTabStops:"),
    (false, "NSMutableParagraphStyle", "setTailIndent:"),
    (false, "NSMutableParagraphStyle", "setTextBlocks:"),
    (true, "NSMutableParagraphStyle", "new"),
    (false, "NSNotification", "object"),
    (false, "NSNotificationCenter", "addObserver:selector:name:object:"),
    (false, "NSNotificationCenter", "addObserverForName:object:queue:usingBlock:"),
    (false, "NSNotificationCenter", "postNotificationName:object:"),
    (false, "NSNotificationCenter", "removeObserver:"),
    (true, "NSNotificationCenter", "defaultCenter"),
    (false, "NSNumber", "boolValue"),
    (false, "NSNumber", "doubleValue"),
    (false, "NSNumber", "floatValue"),
    (false, "NSNumber", "integerValue"),
    (true, "NSNumber", "numberWithDouble:"),
    (true, "NSNumber", "numberWithInteger:"),
    (false, "NSObject", "init"),
    (false, "NSObject", "isEqual:"),
    (false, "NSObject", "isKindOfClass:"),
    (true, "NSObject", "alloc"),
    (false, "NSOpenPanel", "URLs"),
    (false, "NSOpenPanel", "setAllowsMultipleSelection:"),
    (false, "NSOpenPanel", "setCanChooseDirectories:"),
    (false, "NSOpenPanel", "setCanChooseFiles:"),
    (true, "NSOpenPanel", "openPanel"),
    (true, "NSOperationQueue", "mainQueue"),
    (false, "NSPanel", "animator"),
    (false, "NSPanel", "initWithContentRect:styleMask:backing:defer:"),
    (true, "NSPanel", "alloc"),
    (false, "NSParagraphStyle", "firstLineHeadIndent"),
    (false, "NSParagraphStyle", "headIndent"),
    (false, "NSParagraphStyle", "mutableCopy"),
    (false, "NSParagraphStyle", "paragraphSpacing"),
    (false, "NSParagraphStyle", "paragraphSpacingBefore"),
    (false, "NSPasteboard", "availableTypeFromArray:"),
    (false, "NSPasteboard", "clearContents"),
    (false, "NSPasteboard", "dataForType:"),
    (false, "NSPasteboard", "declareTypes:owner:"),
    (false, "NSPasteboard", "pasteboardItems"),
    (false, "NSPasteboard", "setData:forType:"),
    (false, "NSPasteboard", "setString:forType:"),
    (false, "NSPasteboard", "stringForType:"),
    (false, "NSPasteboard", "types"),
    (true, "NSPasteboard", "generalPasteboard"),
    (false, "NSPasteboardItem", "stringForType:"),
    (false, "NSPopUpButton", "addItemWithTitle:"),
    (false, "NSPopUpButton", "addItemsWithTitles:"),
    (false, "NSPopUpButton", "indexOfSelectedItem"),
    (false, "NSPopUpButton", "initWithFrame:pullsDown:"),
    (false, "NSPopUpButton", "itemAtIndex:"),
    (false, "NSPopUpButton", "removeAllItems"),
    (false, "NSPopUpButton", "selectItemAtIndex:"),
    (false, "NSPopUpButton", "selectItemWithTitle:"),
    (false, "NSPopUpButton", "titleOfSelectedItem"),
    (true, "NSPopUpButton", "alloc"),
    (false, "NSProgressIndicator", "initWithFrame:"),
    (false, "NSProgressIndicator", "setControlSize:"),
    (false, "NSProgressIndicator", "setDisplayedWhenStopped:"),
    (false, "NSProgressIndicator", "setIndeterminate:"),
    (false, "NSProgressIndicator", "setStyle:"),
    (false, "NSProgressIndicator", "startAnimation:"),
    (false, "NSProgressIndicator", "stopAnimation:"),
    (true, "NSProgressIndicator", "alloc"),
    (true, "NSPropertyListSerialization", "propertyListWithData:options:format:error:"),
    (false, "NSRegularExpression", "firstMatchInString:options:range:"),
    (false, "NSRegularExpression", "matchesInString:options:range:"),
    (false, "NSRegularExpression", "rangeOfFirstMatchInString:options:range:"),
    (true, "NSRegularExpression", "regularExpressionWithPattern:options:error:"),
    (false, "NSResponder", "mouseDown:"),
    (false, "NSResponder", "rightMouseDown:"),
    (false, "NSResponder", "setMenu:"),
    (false, "NSResponder", "undoManager"),
    (false, "NSRunLoop", "addTimer:forMode:"),
    (false, "NSRunLoop", "runMode:beforeDate:"),
    (true, "NSRunLoop", "currentRunLoop"),
    (true, "NSRunLoop", "mainRunLoop"),
    (false, "NSRunningApplication", "bundleIdentifier"),
    (false, "NSRunningApplication", "isActive"),
    (false, "NSRunningApplication", "localizedName"),
    (false, "NSRunningApplication", "processIdentifier"),
    (true, "NSRunningApplication", "currentApplication"),
    (false, "NSSavePanel", "runModal"),
    (false, "NSScanner", "scanHexLongLong:"),
    (false, "NSScanner", "setCharactersToBeSkipped:"),
    (true, "NSScanner", "scannerWithString:"),
    (false, "NSScreen", "backingScaleFactor"),
    (false, "NSScreen", "frame"),
    (false, "NSScreen", "visibleFrame"),
    (true, "NSScreen", "mainScreen"),
    (true, "NSScreen", "screens"),
    (false, "NSScrollView", "contentInsets"),
    (false, "NSScrollView", "contentSize"),
    (false, "NSScrollView", "contentView"),
    (false, "NSScrollView", "documentView"),
    (false, "NSScrollView", "documentVisibleRect"),
    (false, "NSScrollView", "initWithFrame:"),
    (false, "NSScrollView", "reflectScrolledClipView:"),
    (false, "NSScrollView", "setAutohidesScrollers:"),
    (false, "NSScrollView", "setAutomaticallyAdjustsContentInsets:"),
    (false, "NSScrollView", "setBackgroundColor:"),
    (false, "NSScrollView", "setBorderType:"),
    (false, "NSScrollView", "setContentInsets:"),
    (false, "NSScrollView", "setDocumentView:"),
    (false, "NSScrollView", "setDrawsBackground:"),
    (false, "NSScrollView", "setHasHorizontalScroller:"),
    (false, "NSScrollView", "setHasVerticalScroller:"),
    (false, "NSScrollView", "setScrollerStyle:"),
    (false, "NSScrollView", "setVerticalLineScroll:"),
    (false, "NSScrollView", "verticalScroller"),
    (true, "NSScrollView", "alloc"),
    (true, "NSScrollView", "new"),
    (false, "NSScroller", "hitPart"),
    (false, "NSScroller", "knobProportion"),
    (true, "NSScroller", "scrollerWidthForControlSize:scrollerStyle:"),
    (false, "NSSearchField", "initWithFrame:"),
    (false, "NSSearchField", "setDelegate:"),
    (false, "NSSearchField", "setSendsSearchStringImmediately:"),
    (true, "NSSearchField", "alloc"),
    (false, "NSSecureTextField", "initWithFrame:"),
    (true, "NSSecureTextField", "alloc"),
    (false, "NSSegmentedControl", "initWithFrame:"),
    (false, "NSSegmentedControl", "mouseDown:"),
    (false, "NSSegmentedControl", "selectedSegment"),
    (false, "NSSegmentedControl", "setEnabled:forSegment:"),
    (false, "NSSegmentedControl", "setLabel:forSegment:"),
    (false, "NSSegmentedControl", "setSegmentCount:"),
    (false, "NSSegmentedControl", "setSegmentDistribution:"),
    (false, "NSSegmentedControl", "setSegmentStyle:"),
    (false, "NSSegmentedControl", "setSelectedSegment:"),
    (false, "NSSegmentedControl", "setToolTip:forSegment:"),
    (false, "NSSegmentedControl", "setTrackingMode:"),
    (true, "NSSegmentedControl", "alloc"),
    (false, "NSSplitView", "adjustSubviews"),
    (false, "NSSplitView", "dividerThickness"),
    (false, "NSSplitView", "initWithFrame:"),
    (false, "NSSplitView", "setAutosaveName:"),
    (false, "NSSplitView", "setDelegate:"),
    (false, "NSSplitView", "setDividerStyle:"),
    (false, "NSSplitView", "setPosition:ofDividerAtIndex:"),
    (false, "NSSplitView", "setVertical:"),
    (true, "NSSplitView", "alloc"),
    (false, "NSStepper", "initWithFrame:"),
    (false, "NSStepper", "setAutorepeat:"),
    (false, "NSStepper", "setIncrement:"),
    (false, "NSStepper", "setMaxValue:"),
    (false, "NSStepper", "setMinValue:"),
    (false, "NSStepper", "setValueWraps:"),
    (true, "NSStepper", "alloc"),
    (false, "NSString", "boundingRectWithSize:options:attributes:context:"),
    (false, "NSString", "capitalizedString"),
    (false, "NSString", "caseInsensitiveCompare:"),
    (false, "NSString", "characterAtIndex:"),
    (false, "NSString", "componentsSeparatedByCharactersInSet:"),
    (false, "NSString", "componentsSeparatedByString:"),
    (false, "NSString", "copy"),
    (false, "NSString", "drawInRect:withAttributes:"),
    (false, "NSString", "enumerateSubstringsInRange:options:usingBlock:"),
    (false, "NSString", "getCharacters:range:"),
    (false, "NSString", "initWithBytes:length:encoding:"),
    (false, "NSString", "initWithCharacters:length:"),
    (false, "NSString", "initWithCharactersNoCopy:length:freeWhenDone:"),
    (false, "NSString", "isEqualToString:"),
    (false, "NSString", "length"),
    (false, "NSString", "lengthOfBytesUsingEncoding:"),
    (false, "NSString", "lineRangeForRange:"),
    (false, "NSString", "localizedStandardCompare:"),
    (false, "NSString", "lowercaseString"),
    (false, "NSString", "paragraphRangeForRange:"),
    (false, "NSString", "rangeOfComposedCharacterSequenceAtIndex:"),
    (false, "NSString", "rangeOfString:"),
    (false, "NSString", "rangeOfString:options:range:"),
    (false, "NSString", "sizeWithAttributes:"),
    (false, "NSString", "stringByExpandingTildeInPath"),
    (false, "NSString", "stringByReplacingOccurrencesOfString:withString:"),
    (false, "NSString", "stringByTrimmingCharactersInSet:"),
    (false, "NSString", "substringToIndex:"),
    (false, "NSString", "substringWithRange:"),
    (true, "NSString", "alloc"),
    (false, "NSTableCellView", "drawRect:"),
    (false, "NSTableCellView", "initWithFrame:"),
    (false, "NSTableCellView", "updateTrackingAreas"),
    (true, "NSTableCellView", "alloc"),
    (false, "NSTableColumn", "initWithIdentifier:"),
    (false, "NSTableColumn", "setResizingMask:"),
    (true, "NSTableColumn", "alloc"),
    (false, "NSTableView", "addTableColumn:"),
    (false, "NSTableView", "clickedRow"),
    (false, "NSTableView", "initWithFrame:"),
    (false, "NSTableView", "keyDown:"),
    (false, "NSTableView", "makeViewWithIdentifier:owner:"),
    (false, "NSTableView", "mouseDown:"),
    (false, "NSTableView", "reloadData"),
    (false, "NSTableView", "rowAtPoint:"),
    (false, "NSTableView", "rowHeight"),
    (false, "NSTableView", "scrollRowToVisible:"),
    (false, "NSTableView", "selectRowIndexes:byExtendingSelection:"),
    (false, "NSTableView", "selectedRow"),
    (false, "NSTableView", "setBackgroundColor:"),
    (false, "NSTableView", "setDataSource:"),
    (false, "NSTableView", "setDelegate:"),
    (false, "NSTableView", "setHeaderView:"),
    (false, "NSTableView", "setIntercellSpacing:"),
    (false, "NSTableView", "setRowHeight:"),
    (false, "NSTableView", "setSelectionHighlightStyle:"),
    (true, "NSTableView", "alloc"),
    (false, "NSTextBlock", "setBackgroundColor:"),
    (false, "NSTextBlock", "setBorderColor:"),
    (false, "NSTextBlock", "setContentWidth:type:"),
    (false, "NSTextBlock", "setWidth:type:forLayer:"),
    (false, "NSTextBlock", "setWidth:type:forLayer:edge:"),
    (true, "NSTextBlock", "new"),
    (false, "NSTextCheckingResult", "numberOfRanges"),
    (false, "NSTextCheckingResult", "range"),
    (false, "NSTextCheckingResult", "rangeAtIndex:"),
    (false, "NSTextContainer", "initWithSize:"),
    (false, "NSTextContainer", "setContainerSize:"),
    (false, "NSTextContainer", "setLineFragmentPadding:"),
    (false, "NSTextContainer", "setSize:"),
    (false, "NSTextContainer", "setWidthTracksTextView:"),
    (false, "NSTextContainer", "size"),
    (true, "NSTextContainer", "alloc"),
    (false, "NSTextField", "initWithFrame:"),
    (false, "NSTextField", "selectText:"),
    (false, "NSTextField", "setBezeled:"),
    (false, "NSTextField", "setDelegate:"),
    (false, "NSTextField", "setDrawsBackground:"),
    (false, "NSTextField", "setEditable:"),
    (false, "NSTextField", "setMaximumNumberOfLines:"),
    (false, "NSTextField", "setPlaceholderString:"),
    (false, "NSTextField", "setSelectable:"),
    (false, "NSTextField", "setTextColor:"),
    (true, "NSTextField", "alloc"),
    (true, "NSTextField", "labelWithString:"),
    (true, "NSTextField", "wrappingLabelWithString:"),
    (false, "NSTextStorage", "addLayoutManager:"),
    (false, "NSTextStorage", "editedMask"),
    (false, "NSTextStorage", "editedRange"),
    (false, "NSTextStorage", "initWithString:"),
    (true, "NSTextStorage", "alloc"),
    (true, "NSTextStorage", "new"),
    (false, "NSTextTab", "initWithTextAlignment:location:options:"),
    (true, "NSTextTab", "alloc"),
    (false, "NSTextTable", "setCollapsesBorders:"),
    (false, "NSTextTable", "setHidesEmptyCells:"),
    (false, "NSTextTable", "setLayoutAlgorithm:"),
    (false, "NSTextTable", "setNumberOfColumns:"),
    (true, "NSTextTable", "new"),
    (false, "NSTextTableBlock", "initWithTable:startingRow:rowSpan:startingColumn:columnSpan:"),
    (true, "NSTextTableBlock", "alloc"),
    (false, "NSTextView", "characterIndexForInsertionAtPoint:"),
    (false, "NSTextView", "clickedOnLink:atIndex:"),
    (false, "NSTextView", "concludeDragOperation:"),
    (false, "NSTextView", "deleteBackward:"),
    (false, "NSTextView", "deleteForward:"),
    (false, "NSTextView", "deleteToBeginningOfLine:"),
    (false, "NSTextView", "deleteToBeginningOfParagraph:"),
    (false, "NSTextView", "deleteToEndOfLine:"),
    (false, "NSTextView", "deleteToEndOfParagraph:"),
    (false, "NSTextView", "deleteWordBackward:"),
    (false, "NSTextView", "deleteWordForward:"),
    (false, "NSTextView", "didChangeText"),
    (false, "NSTextView", "draggingEntered:"),
    (false, "NSTextView", "draggingExited:"),
    (false, "NSTextView", "draggingUpdated:"),
    (false, "NSTextView", "drawRect:"),
    (false, "NSTextView", "drawViewBackgroundInRect:"),
    (false, "NSTextView", "hasMarkedText"),
    (false, "NSTextView", "initWithFrame:"),
    (false, "NSTextView", "initWithFrame:textContainer:"),
    (false, "NSTextView", "insertNewline:"),
    (false, "NSTextView", "insertNewlineIgnoringFieldEditor:"),
    (false, "NSTextView", "insertText:replacementRange:"),
    (false, "NSTextView", "invalidateTextContainerOrigin"),
    (false, "NSTextView", "isEditable"),
    (false, "NSTextView", "keyDown:"),
    (false, "NSTextView", "layoutManager"),
    (false, "NSTextView", "menuForEvent:"),
    (false, "NSTextView", "mouseDown:"),
    (false, "NSTextView", "mouseExited:"),
    (false, "NSTextView", "mouseMoved:"),
    (false, "NSTextView", "paste:"),
    (false, "NSTextView", "performDragOperation:"),
    (false, "NSTextView", "prepareForDragOperation:"),
    (false, "NSTextView", "replaceCharactersInRange:withString:"),
    (false, "NSTextView", "scrollRangeToVisible:"),
    (false, "NSTextView", "scrollWheel:"),
    (false, "NSTextView", "selectAll:"),
    (false, "NSTextView", "selectedRange"),
    (false, "NSTextView", "selectedRanges"),
    (false, "NSTextView", "setAllowsUndo:"),
    (false, "NSTextView", "setAutomaticDashSubstitutionEnabled:"),
    (false, "NSTextView", "setAutomaticQuoteSubstitutionEnabled:"),
    (false, "NSTextView", "setAutomaticSpellingCorrectionEnabled:"),
    (false, "NSTextView", "setAutomaticTextReplacementEnabled:"),
    (false, "NSTextView", "setBackgroundColor:"),
    (false, "NSTextView", "setDelegate:"),
    (false, "NSTextView", "setDrawsBackground:"),
    (false, "NSTextView", "setEditable:"),
    (false, "NSTextView", "setFieldEditor:"),
    (false, "NSTextView", "setFont:"),
    (false, "NSTextView", "setHorizontallyResizable:"),
    (false, "NSTextView", "setImportsGraphics:"),
    (false, "NSTextView", "setIncrementalSearchingEnabled:"),
    (false, "NSTextView", "setInsertionPointColor:"),
    (false, "NSTextView", "setLinkTextAttributes:"),
    (false, "NSTextView", "setMarkedText:selectedRange:replacementRange:"),
    (false, "NSTextView", "setMaxSize:"),
    (false, "NSTextView", "setMinSize:"),
    (false, "NSTextView", "setRichText:"),
    (false, "NSTextView", "setSelectable:"),
    (false, "NSTextView", "setSelectedRange:"),
    (false, "NSTextView", "setSelectedRanges:affinity:stillSelecting:"),
    (false, "NSTextView", "setSelectedTextAttributes:"),
    (false, "NSTextView", "setSmartInsertDeleteEnabled:"),
    (false, "NSTextView", "setString:"),
    (false, "NSTextView", "setTextColor:"),
    (false, "NSTextView", "setTextContainerInset:"),
    (false, "NSTextView", "setTypingAttributes:"),
    (false, "NSTextView", "setUsesFindBar:"),
    (false, "NSTextView", "setUsesFontPanel:"),
    (false, "NSTextView", "setVerticallyResizable:"),
    (false, "NSTextView", "shouldChangeTextInRange:replacementString:"),
    (false, "NSTextView", "string"),
    (false, "NSTextView", "swipeWithEvent:"),
    (false, "NSTextView", "textContainer"),
    (false, "NSTextView", "textContainerInset"),
    (false, "NSTextView", "textContainerOrigin"),
    (false, "NSTextView", "textLayoutManager"),
    (false, "NSTextView", "textStorage"),
    (false, "NSTextView", "unmarkText"),
    (false, "NSTextView", "updateTrackingAreas"),
    (false, "NSTextView", "validateMenuItem:"),
    (false, "NSTextView", "viewDidMoveToWindow"),
    (true, "NSTextView", "alloc"),
    (true, "NSTextView", "scrollableTextView"),
    (true, "NSThread", "isMainThread"),
    (false, "NSTimer", "invalidate"),
    (false, "NSTimer", "setFireDate:"),
    (true, "NSTimer", "timerWithTimeInterval:repeats:block:"),
    (true, "NSTimer", "timerWithTimeInterval:target:selector:userInfo:repeats:"),
    (false, "NSTrackingArea", "initWithRect:options:owner:userInfo:"),
    (true, "NSTrackingArea", "alloc"),
    (false, "NSURL", "URLByAppendingPathComponent:"),
    (false, "NSURL", "URLByAppendingPathComponent:isDirectory:"),
    (false, "NSURL", "URLByDeletingLastPathComponent"),
    (false, "NSURL", "URLByDeletingPathExtension"),
    (false, "NSURL", "URLByResolvingSymlinksInPath"),
    (false, "NSURL", "absoluteString"),
    (false, "NSURL", "absoluteURL"),
    (false, "NSURL", "isFileURL"),
    (false, "NSURL", "lastPathComponent"),
    (false, "NSURL", "path"),
    (false, "NSURL", "pathComponents"),
    (false, "NSURL", "pathExtension"),
    (false, "NSURL", "resourceSpecifier"),
    (false, "NSURL", "scheme"),
    (false, "NSURL", "standardizedURL"),
    (true, "NSURL", "URLWithString:"),
    (true, "NSURL", "fileURLWithPath:"),
    (true, "NSURL", "fileURLWithPath:isDirectory:"),
    (true, "NSURL", "fileURLWithPath:relativeToURL:"),
    (false, "NSURLComponents", "host"),
    (false, "NSURLComponents", "path"),
    (false, "NSURLComponents", "scheme"),
    (true, "NSURLComponents", "componentsWithString:"),
    (false, "NSUndoManager", "beginUndoGrouping"),
    (false, "NSUndoManager", "endUndoGrouping"),
    (false, "NSUndoManager", "groupingLevel"),
    (false, "NSUserDefaults", "setObject:forKey:"),
    (false, "NSUserDefaults", "stringForKey:"),
    (true, "NSUserDefaults", "standardUserDefaults"),
    (false, "NSValue", "isEqualToValue:"),
    (false, "NSValue", "rangeValue"),
    (true, "NSValue", "valueWithCATransform3D:"),
    (true, "NSValue", "valueWithRange:"),
    (false, "NSView", "addCursorRect:cursor:"),
    (false, "NSView", "addSubview:"),
    (false, "NSView", "addSubview:positioned:relativeTo:"),
    (false, "NSView", "addTrackingArea:"),
    (false, "NSView", "animator"),
    (false, "NSView", "bitmapImageRepForCachingDisplayInRect:"),
    (false, "NSView", "bottomAnchor"),
    (false, "NSView", "bounds"),
    (false, "NSView", "cacheDisplayInRect:toBitmapImageRep:"),
    (false, "NSView", "centerYAnchor"),
    (false, "NSView", "convertPoint:fromView:"),
    (false, "NSView", "convertPoint:toView:"),
    (false, "NSView", "convertRect:fromView:"),
    (false, "NSView", "convertRect:toView:"),
    (false, "NSView", "displayIfNeeded"),
    (false, "NSView", "displayLinkWithTarget:selector:"),
    (false, "NSView", "displayRect:"),
    (false, "NSView", "drawRect:"),
    (false, "NSView", "effectiveAppearance"),
    (false, "NSView", "enclosingScrollView"),
    (false, "NSView", "fittingSize"),
    (false, "NSView", "frame"),
    (false, "NSView", "initWithFrame:"),
    (false, "NSView", "isHidden"),
    (false, "NSView", "layer"),
    (false, "NSView", "layout"),
    (false, "NSView", "layoutSubtreeIfNeeded"),
    (false, "NSView", "leadingAnchor"),
    (false, "NSView", "registerForDraggedTypes:"),
    (false, "NSView", "registeredDraggedTypes"),
    (false, "NSView", "removeFromSuperview"),
    (false, "NSView", "removeTrackingArea:"),
    (false, "NSView", "scrollPoint:"),
    (false, "NSView", "scrollRectToVisible:"),
    (false, "NSView", "setAccessibilityElement:"),
    (false, "NSView", "setAccessibilityEnabled:"),
    (false, "NSView", "setAccessibilityHelp:"),
    (false, "NSView", "setAccessibilityLabel:"),
    (false, "NSView", "setAccessibilityRole:"),
    (false, "NSView", "setAccessibilityValueDescription:"),
    (false, "NSView", "setAlphaValue:"),
    (false, "NSView", "setAppearance:"),
    (false, "NSView", "setAutoresizingMask:"),
    (false, "NSView", "setFrame:"),
    (false, "NSView", "setFrameOrigin:"),
    (false, "NSView", "setFrameSize:"),
    (false, "NSView", "setHidden:"),
    (false, "NSView", "setIdentifier:"),
    (false, "NSView", "setLayer:"),
    (false, "NSView", "setNeedsDisplay:"),
    (false, "NSView", "setNeedsDisplayInRect:"),
    (false, "NSView", "setNeedsLayout:"),
    (false, "NSView", "setPostsBoundsChangedNotifications:"),
    (false, "NSView", "setPostsFrameChangedNotifications:"),
    (false, "NSView", "setToolTip:"),
    (false, "NSView", "setTranslatesAutoresizingMaskIntoConstraints:"),
    (false, "NSView", "setWantsLayer:"),
    (false, "NSView", "subviews"),
    (false, "NSView", "superview"),
    (false, "NSView", "toolTip"),
    (false, "NSView", "topAnchor"),
    (false, "NSView", "trailingAnchor"),
    (false, "NSView", "unregisterDraggedTypes"),
    (false, "NSView", "updateLayer"),
    (false, "NSView", "updateTrackingAreas"),
    (false, "NSView", "viewDidChangeEffectiveAppearance"),
    (false, "NSView", "viewDidMoveToWindow"),
    (false, "NSView", "visibleRect"),
    (false, "NSView", "wantsUpdateLayer"),
    (false, "NSView", "window"),
    (true, "NSView", "alloc"),
    (false, "NSVisualEffectView", "drawRect:"),
    (false, "NSVisualEffectView", "initWithFrame:"),
    (false, "NSVisualEffectView", "setBlendingMode:"),
    (false, "NSVisualEffectView", "setMaterial:"),
    (false, "NSVisualEffectView", "setState:"),
    (false, "NSVisualEffectView", "updateTrackingAreas"),
    (true, "NSVisualEffectView", "alloc"),
    (false, "NSWindow", "addChildWindow:ordered:"),
    (false, "NSWindow", "animator"),
    (false, "NSWindow", "attachedSheet"),
    (false, "NSWindow", "backingScaleFactor"),
    (false, "NSWindow", "beginSheet:completionHandler:"),
    (false, "NSWindow", "center"),
    (false, "NSWindow", "close"),
    (false, "NSWindow", "contentView"),
    (false, "NSWindow", "convertPointToScreen:"),
    (false, "NSWindow", "convertRectToScreen:"),
    (false, "NSWindow", "displayIfNeeded"),
    (false, "NSWindow", "endSheet:"),
    (false, "NSWindow", "firstResponder"),
    (false, "NSWindow", "frame"),
    (false, "NSWindow", "initWithContentRect:styleMask:backing:defer:"),
    (false, "NSWindow", "invalidateCursorRectsForView:"),
    (false, "NSWindow", "isKeyWindow"),
    (false, "NSWindow", "isVisible"),
    (false, "NSWindow", "makeFirstResponder:"),
    (false, "NSWindow", "makeKeyAndOrderFront:"),
    (false, "NSWindow", "makeKeyWindow"),
    (false, "NSWindow", "occlusionState"),
    (false, "NSWindow", "orderFront:"),
    (false, "NSWindow", "orderFrontRegardless"),
    (false, "NSWindow", "orderOut:"),
    (false, "NSWindow", "parentWindow"),
    (false, "NSWindow", "removeChildWindow:"),
    (false, "NSWindow", "screen"),
    (false, "NSWindow", "setAlphaValue:"),
    (false, "NSWindow", "setAnimationBehavior:"),
    (false, "NSWindow", "setBackgroundColor:"),
    (false, "NSWindow", "setContentMinSize:"),
    (false, "NSWindow", "setContentSize:"),
    (false, "NSWindow", "setContentView:"),
    (false, "NSWindow", "setDelegate:"),
    (false, "NSWindow", "setFrame:display:"),
    (false, "NSWindow", "setFrame:display:animate:"),
    (false, "NSWindow", "setFrameAutosaveName:"),
    (false, "NSWindow", "setFrameOrigin:"),
    (false, "NSWindow", "setFrameUsingName:"),
    (false, "NSWindow", "setHasShadow:"),
    (false, "NSWindow", "setHidesOnDeactivate:"),
    (false, "NSWindow", "setIgnoresMouseEvents:"),
    (false, "NSWindow", "setLevel:"),
    (false, "NSWindow", "setMinSize:"),
    (false, "NSWindow", "setMovableByWindowBackground:"),
    (false, "NSWindow", "setOpaque:"),
    (false, "NSWindow", "setReleasedWhenClosed:"),
    (false, "NSWindow", "setTitle:"),
    (false, "NSWindow", "setTitleVisibility:"),
    (false, "NSWindow", "setTitlebarAppearsTransparent:"),
    (false, "NSWindow", "title"),
    (false, "NSWindow", "windowNumber"),
    (true, "NSWindow", "alloc"),
    (false, "NSWorkspace", "accessibilityDisplayShouldIncreaseContrast"),
    (false, "NSWorkspace", "accessibilityDisplayShouldReduceMotion"),
    (false, "NSWorkspace", "accessibilityDisplayShouldReduceTransparency"),
    (false, "NSWorkspace", "activateFileViewerSelectingURLs:"),
    (false, "NSWorkspace", "frontmostApplication"),
    (false, "NSWorkspace", "openURL:"),
    (true, "NSWorkspace", "sharedWorkspace"),
];

fn class(name: &str) -> &'static AnyClass {
    AnyClass::get(&CString::new(name).unwrap()).unwrap_or_else(|| panic!("no class {name}"))
}

fn object<T: objc2::Message>(value: Retained<T>) -> Retained<AnyObject> {
    // SAFETY: every object is an AnyObject.
    unsafe { Retained::cast_unchecked(value) }
}

fn frame() -> NSRect {
    NSRect::new(NSPoint::ZERO, NSSize::new(100.0, 100.0))
}

/// Real instances of `name`, several for classes whose instances come in
/// several concrete classes; none for classes this file doesn't make.
fn instances(mtm: MainThreadMarker, name: &str) -> Vec<Retained<AnyObject>> {
    let cls = class(name);
    let new = || -> Retained<AnyObject> { unsafe { msg_send![cls, new] } };
    let view = || -> Retained<AnyObject> {
        let a: Allocated<AnyObject> = unsafe { msg_send![cls, alloc] };
        unsafe { msg_send![a, initWithFrame: frame()] }
    };
    let s = |t: &str| object(NSString::from_str(t));
    unsafe {
        match name {
            "NSView"
            | "NSBox"
            | "NSButton"
            | "NSClipView"
            | "NSControl"
            | "NSPopUpButton"
            | "NSProgressIndicator"
            | "NSScrollView"
            | "NSScroller"
            | "NSSearchField"
            | "NSSecureTextField"
            | "NSSegmentedControl"
            | "NSSplitView"
            | "NSStepper"
            | "NSTableCellView"
            | "NSTableView"
            | "NSTextField"
            | "NSTextView"
            | "NSVisualEffectView" => vec![view()],
            "NSResponder"
            | "NSAlert"
            | "NSMenu"
            | "NSMenuItem"
            | "NSPasteboardItem"
            | "NSLayoutManager"
            | "NSTextStorage"
            | "NSMutableParagraphStyle"
            | "NSURLComponents"
            | "NSUndoManager"
            | "NSObject"
            | "NSMutableAttributedString"
            | "NSMutableDictionary"
            | "NSBezierPath"
            | "NSTextBlock"
            | "NSTextTable" => {
                vec![new()]
            }
            "NSWindow" | "NSPanel" => {
                let a: Allocated<AnyObject> = msg_send![cls, alloc];
                let w: Retained<AnyObject> = msg_send![a, initWithContentRect: frame(), styleMask: NSWindowStyleMask::Titled, backing: NSBackingStoreType::Buffered, defer: true];
                let _: () = msg_send![&*w, setReleasedWhenClosed: false];
                vec![w]
            }
            "NSApplication" => vec![object(NSApplication::sharedApplication(mtm))],
            "NSColor" => vec![
                object(NSColor::redColor()),
                object(NSColor::colorWithSRGBRed_green_blue_alpha(0.1, 0.2, 0.3, 1.0)),
                object(NSColor::colorWithWhite_alpha(0.5, 1.0)),
                object(NSColor::controlTextColor()),
                object(NSColor::windowBackgroundColor()),
            ],
            "NSFont" => vec![object(NSFont::systemFontOfSize(12.0))],
            "NSFontDescriptor" => vec![object(NSFont::systemFontOfSize(12.0).fontDescriptor())],
            "NSImage" => vec![object(NSImage::initWithSize(NSImage::alloc(), NSSize::new(4.0, 4.0)))],
            "NSCursor" => vec![msg_send![cls, arrowCursor]],
            "NSEvent" => vec![object(
                NSEvent::otherEventWithType_location_modifierFlags_timestamp_windowNumber_context_subtype_data1_data2(
                    NSEventType::ApplicationDefined,
                    NSPoint::ZERO,
                    NSEventModifierFlags::empty(),
                    0.0,
                    0,
                    None,
                    0,
                    0,
                    0,
                )
                .expect("an event"),
            )],
            "NSPasteboard" => vec![msg_send![cls, generalPasteboard]],
            "NSRunningApplication" => vec![msg_send![cls, currentApplication]],
            "NSWorkspace" => vec![msg_send![cls, sharedWorkspace]],
            "NSAnimationContext" => vec![msg_send![cls, currentContext]],
            "NSParagraphStyle" => vec![msg_send![cls, defaultParagraphStyle]],
            "NSTextContainer" => {
                let a: Allocated<AnyObject> = msg_send![cls, alloc];
                vec![msg_send![a, initWithSize: NSSize::new(100.0, 100.0)]]
            }
            "NSTableColumn" => {
                let a: Allocated<AnyObject> = msg_send![cls, alloc];
                vec![msg_send![a, initWithIdentifier: &*s("c")]]
            }
            "NSString" => vec![s("text"), s(""), object(NSString::from_str("a longer string than a tagged one fits"))],
            "NSAttributedString" => {
                let a: Allocated<AnyObject> = msg_send![cls, alloc];
                vec![msg_send![a, initWithString: &*s("text")]]
            }
            "NSArray" => vec![msg_send![cls, arrayWithObject: &*s("x")], msg_send![cls, array]],
            "NSDictionary" => {
                vec![msg_send![cls, dictionaryWithObject: &*s("v"), forKey: &*s("k")], msg_send![cls, dictionary]]
            }
            "NSNumber" => vec![
                msg_send![cls, numberWithInt: 1i32],
                msg_send![cls, numberWithDouble: 1.5f64],
                msg_send![cls, numberWithBool: true],
            ],
            "NSValue" => vec![object(NSValue::valueWithRange(NSRange::new(0, 1)))],
            "NSData" => vec![
                msg_send![cls, dataWithBytes: b"ab".as_ptr().cast::<std::ffi::c_void>(), length: 2usize],
                msg_send![cls, data],
            ],
            "NSDate" => vec![msg_send![cls, date]],
            "NSURL" => vec![
                object(NSURL::fileURLWithPath(&NSString::from_str("/tmp"))),
                object(NSURL::URLWithString(&NSString::from_str("https://example.com/a")).unwrap()),
            ],
            "NSError" => {
                vec![msg_send![cls, errorWithDomain: &*s("d"), code: 1isize, userInfo: std::ptr::null::<AnyObject>()]]
            }
            "NSIndexSet" => vec![msg_send![cls, indexSetWithIndex: 1usize]],
            "NSCharacterSet" => vec![msg_send![cls, whitespaceCharacterSet]],
            "NSScanner" => vec![msg_send![cls, scannerWithString: &*s("1 2")]],
            "NSRegularExpression" => {
                vec![
                    msg_send![cls, regularExpressionWithPattern: &*s("a+"), options: 0usize, error: std::ptr::null_mut::<*mut AnyObject>()],
                ]
            }
            "NSDateFormatter" => vec![new()],
            "NSBundle" => vec![msg_send![cls, mainBundle]],
            "NSFileManager" => vec![msg_send![cls, defaultManager]],
            "NSNotification" => {
                vec![msg_send![cls, notificationWithName: &*s("n"), object: std::ptr::null::<AnyObject>()]]
            }
            "NSNotificationCenter" => vec![msg_send![cls, defaultCenter]],
            "NSOperationQueue" => vec![msg_send![cls, mainQueue]],
            "NSRunLoop" => vec![msg_send![cls, currentRunLoop]],
            "NSThread" => vec![msg_send![cls, currentThread]],
            "NSUserDefaults" => vec![msg_send![cls, standardUserDefaults]],
            "NSAppearance" => vec![msg_send![cls, appearanceNamed: &*s("NSAppearanceNameAqua")]],
            "NSColorSpace" => vec![msg_send![cls, sRGBColorSpace]],
            _ => Vec::new(),
        }
    }
}

fn main() {
    let mtm = MainThreadMarker::new().expect("the test's main runs on the main thread");
    let app = NSApplication::sharedApplication(mtm);
    app.setActivationPolicy(NSApplicationActivationPolicy::Accessory);
    if !cfg!(debug_assertions) {
        println!("test every_sent_selector_responds ... ignored (debug builds)");
        return;
    }
    let mut missing = Vec::new();
    let mut made: std::collections::HashMap<&str, Vec<Retained<AnyObject>>> = Default::default();
    for &(class_method, name, selector) in SENT {
        let sel = Sel::register(&CString::new(selector).unwrap());
        let cls = class(name);
        if class_method {
            let responds: bool = unsafe { msg_send![cls, respondsToSelector: sel] };
            if !responds {
                missing.push(format!("+[{name} {selector}]"));
            }
            continue;
        }
        // Initializers belong to allocated objects, not made ones.
        let objects = made.entry(name).or_insert_with(|| instances(mtm, name));
        if objects.is_empty() || selector.starts_with("init") {
            let mut responds: bool = unsafe { msg_send![cls, instancesRespondToSelector: sel] };
            if !responds && selector.starts_with("init") {
                // A class cluster: its placeholder initializes. Kept, not
                // given back uninitialized.
                let allocated: Allocated<AnyObject> = unsafe { msg_send![cls, alloc] };
                responds = unsafe { msg_send![Allocated::as_ptr(&allocated), respondsToSelector: sel] };
                std::mem::forget(allocated);
            }
            if !responds {
                missing.push(format!("-[{name} {selector}]"));
            }
            continue;
        }
        for object in objects.iter() {
            let responds: bool = unsafe { msg_send![&**object, respondsToSelector: sel] };
            if !responds {
                missing.push(format!("-[{name} {selector}] on a {}", object.class().name().to_str().unwrap()));
            }
        }
    }
    assert!(missing.is_empty(), "{} selectors not found:\n{}", missing.len(), missing.join("\n"));
    println!("test every_sent_selector_responds ... ok");
}
