[package]
name = "controls-gallery"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
objc2.workspace = true
block2.workspace = true
objc2-foundation = { workspace = true, features = ["NSString", "NSObject", "NSThread", "NSTimer", "NSDate", "NSDictionary", "NSGeometry", "NSNotification", "NSZone", "NSArray", "NSAttributedString", "block2"] }
objc2-app-kit = { workspace = true, features = ["NSApplication", "NSResponder", "NSView", "NSWindow", "NSGraphics", "NSColor", "NSFont", "NSEvent", "NSRunningApplication", "NSControl", "NSCell", "NSActionCell", "NSButton", "NSButtonCell", "NSTextField", "NSTextFieldCell", "NSSecureTextField", "NSSearchField", "NSSearchFieldCell", "NSBox", "NSProgressIndicator", "NSSegmentedControl", "NSSegmentedCell", "NSStepper", "NSSlider", "NSSliderCell", "NSSwitch", "NSText", "NSParagraphStyle", "objc2-core-foundation", "NSImage", "NSImageView", "NSImageCell", "NSBezierPath", "block2"] }
sidestep.workspace = true
