//! Constants objc2-foundation declares that no class here reads yet,
//! exported so that programs naming them link: string constants with the
//! values macOS gives them (read by running a program against Foundation
//! there), and a few plain values.

use objc2_foundation::{NSEdgeInsets, NSPoint, NSRect, NSSize};

macro_rules! constants {
    ($($name:ident = $value:literal,)*) => {
        $(crate::constant_string!($name = $value);)*
    };
}

constants! {
    // NSAttributedString
    NSInflectionConceptsKey = "NSContextInflectionConcepts",
    NSInlinePresentationIntentAttributeName = "NSInlinePresentationIntent",
    NSAlternateDescriptionAttributeName = "NSAlternateDescription",
    NSImageURLAttributeName = "NSImageURL",
    NSLanguageIdentifierAttributeName = "NSLanguage",
    NSMarkdownSourcePositionAttributeName = "NSMarkdownSourcePosition",
    NSReplacementIndexAttributeName = "NSReplacementIndex",
    NSMorphologyAttributeName = "NSMorphology",
    NSInflectionRuleAttributeName = "NSInflect",
    NSInflectionAgreementArgumentAttributeName = "NSInflectionAgreementArgument",
    NSInflectionAgreementConceptAttributeName = "NSInflectionAgreementConcept",
    NSInflectionReferentConceptAttributeName = "NSInflectionReferentConcept",
    NSInflectionAlternativeAttributeName = "NSInflectionAlternative",
    NSLocalizedNumberFormatAttributeName = "NSLocalizedNumberFormat",
    NSListItemDelimiterAttributeName = "NSListItemDelimiter",
    NSPresentationIntentAttributeName = "NSPresentationIntent",
    // NSBundle
    NSBundleDidLoadNotification = "NSBundleDidLoadNotification",
    NSLoadedClasses = "NSLoadedClasses",
    NSBundleResourceRequestLowDiskSpaceNotification = "NSBundleResourceRequestLowDiskSpaceNotification",
    // NSDate
    NSSystemClockDidChangeNotification = "NSSystemClockDidChangeNotification",
    // NSException
    NSGenericException = "NSGenericException",
    NSRangeException = "NSRangeException",
    NSInvalidArgumentException = "NSInvalidArgumentException",
    NSInternalInconsistencyException = "NSInternalInconsistencyException",
    NSMallocException = "NSMallocException",
    NSObjectInaccessibleException = "NSObjectInaccessibleException",
    NSObjectNotAvailableException = "NSObjectNotAvailableException",
    NSDestinationInvalidException = "NSDestinationInvalidException",
    NSPortTimeoutException = "NSPortTimeoutException",
    NSInvalidSendPortException = "NSInvalidSendPortException",
    NSInvalidReceivePortException = "NSInvalidReceivePortException",
    NSPortSendException = "NSPortSendException",
    NSPortReceiveException = "NSPortReceiveException",
    NSOldStyleException = "NSOldStyleException",
    NSInconsistentArchiveException = "NSArchiverArchiveInconsistency",
    NSAssertionHandlerKey = "NSAssertionHandler",
    // NSExtensionContext
    NSExtensionItemsAndErrorsKey = "NSExtensionItemsAndErrorsKey",
    NSExtensionHostWillEnterForegroundNotification = "NSExtensionHostWillEnterForegroundNotification",
    NSExtensionHostDidEnterBackgroundNotification = "NSExtensionHostDidEnterBackgroundNotification",
    NSExtensionHostWillResignActiveNotification = "NSExtensionHostWillResignActiveNotification",
    NSExtensionHostDidBecomeActiveNotification = "NSExtensionHostDidBecomeActiveNotification",
    // NSFileManager
    NSFileManagerUnmountDissentingProcessIdentifierErrorKey = "NSFileManagerUnmountDissentingProcessIdentifierErrorKey",
    NSUbiquityIdentityDidChangeNotification = "NSUbiquityIdentityDidChangeNotification",
    // NSItemProvider
    NSItemProviderPreferredImageSizeKey = "NSItemProviderPreferredImageSize",
    NSExtensionJavaScriptPreprocessingResultsKey = "NSExtensionJavaScriptPreprocessingResultsKey",
    NSExtensionJavaScriptFinalizeArgumentKey = "NSExtensionJavaScriptFinalizeArgumentKey",
    NSItemProviderErrorDomain = "NSItemProviderErrorDomain",
    // NSLocale (its keys are CoreFoundation's: cf/locale.rs)
    NSGregorianCalendar = "gregorian",
    NSBuddhistCalendar = "buddhist",
    NSChineseCalendar = "chinese",
    NSHebrewCalendar = "hebrew",
    NSIslamicCalendar = "islamic",
    NSIslamicCivilCalendar = "islamic-civil",
    NSJapaneseCalendar = "japanese",
    NSRepublicOfChinaCalendar = "roc",
    NSPersianCalendar = "persian",
    NSIndianCalendar = "indian",
    NSISO8601Calendar = "iso8601",
    // NSOperation
    NSInvocationOperationVoidResultException = "NSInvocationOperationVoidResultException",
    NSInvocationOperationCancelledException = "NSInvocationOperationCancelledException",
    // NSProcessInfo
    NSProcessInfoThermalStateDidChangeNotification = "NSProcessInfoThermalStateDidChangeNotification",
    NSProcessInfoPowerStateDidChangeNotification = "NSProcessInfoPowerStateDidChangeNotification",
    // NSProgress
    NSProgressEstimatedTimeRemainingKey = "NSProgressEstimatedTimeRemainingKey",
    NSProgressThroughputKey = "NSProgressThroughputKey",
    NSProgressKindFile = "NSProgressKindFile",
    NSProgressFileOperationKindKey = "NSProgressFileOperationKindKey",
    NSProgressFileOperationKindDownloading = "NSProgressFileOperationKindDownloading",
    NSProgressFileOperationKindDecompressingAfterDownloading = "NSProgressFileOperationKindDecompressingAfterDownloading",
    NSProgressFileOperationKindReceiving = "NSProgressFileOperationKindReceiving",
    NSProgressFileOperationKindCopying = "NSProgressFileOperationKindCopying",
    NSProgressFileOperationKindUploading = "NSProgressFileOperationKindUploading",
    NSProgressFileOperationKindDuplicating = "NSProgressFileOperationKindDuplicating",
    NSProgressFileURLKey = "NSProgressFileURLKey",
    NSProgressFileTotalCountKey = "NSProgressFileTotalCountKey",
    NSProgressFileCompletedCountKey = "NSProgressFileCompletedCountKey",
    NSProgressFileAnimationImageKey = "NSProgressFlyToImageKey",
    NSProgressFileAnimationImageOriginalRectKey = "NSProgressFileAnimationImageOriginalRectKey",
    NSProgressFileIconKey = "NSProgressFileIconKey",
    // NSString
    NSStringEncodingDetectionSuggestedEncodingsKey = "NSStringEncodingDetectionSuggestedEncodingsKey",
    NSStringEncodingDetectionDisallowedEncodingsKey = "NSStringEncodingDetectionDisallowedEncodingsKey",
    NSStringEncodingDetectionUseOnlySuggestedEncodingsKey = "NSStringEncodingDetectionUseOnlySuggestedEncodingsKey",
    NSStringEncodingDetectionAllowLossyKey = "NSStringEncodingDetectionAllowLossyKey",
    NSStringEncodingDetectionFromWindowsKey = "NSStringEncodingDetectionFromWindowsKey",
    NSStringEncodingDetectionLossySubstitutionKey = "NSStringEncodingDetectionLossySubstitutionKey",
    NSStringEncodingDetectionLikelyLanguageKey = "NSStringEncodingDetectionLikelyLanguageKey",
    NSCharacterConversionException = "NSCharacterConversionException",
    NSParseErrorException = "NSParseErrorException",
    // NSTextCheckingResult
    NSTextCheckingNameKey = "Name",
    NSTextCheckingJobTitleKey = "JobTitle",
    NSTextCheckingOrganizationKey = "Organization",
    NSTextCheckingStreetKey = "Street",
    NSTextCheckingCityKey = "City",
    NSTextCheckingStateKey = "State",
    NSTextCheckingZIPKey = "ZIP",
    NSTextCheckingCountryKey = "Country",
    NSTextCheckingPhoneKey = "Phone",
    NSTextCheckingAirlineKey = "Airline",
    NSTextCheckingFlightKey = "Flight",
    // NSURL
    NSURLFileScheme = "file",
    NSURLKeysOfUnsetValuesKey = "NSURLKeysOfUnsetValuesKey",
    NSURLIsApplicationKey = "_NSURLIsApplicationKey",
    NSURLApplicationIsScriptableKey = "NSURLApplicationIsScriptableKey",
    NSURLIsSystemImmutableKey = "NSURLIsSystemImmutableKey",
    NSURLIsUserImmutableKey = "NSURLIsUserImmutableKey",
    NSURLLocalizedTypeDescriptionKey = "NSURLLocalizedTypeDescriptionKey",
    NSURLLabelNumberKey = "NSURLLabelNumberKey",
    NSURLLabelColorKey = "NSURLLabelColorKey",
    NSURLLocalizedLabelKey = "NSURLLocalizedLabelKey",
    NSURLEffectiveIconKey = "NSURLEffectiveIconKey",
    NSURLCustomIconKey = "NSURLCustomIconKey",
    NSURLVolumeIdentifierKey = "NSURLVolumeIdentifierKey",
    NSURLFileSecurityKey = "NSURLFileSecurityKey",
    NSURLIsExcludedFromBackupKey = "NSURLIsExcludedFromBackupKey",
    NSURLTagNamesKey = "NSURLTagNamesKey",
    NSURLIsMountTriggerKey = "NSURLIsMountTriggerKey",
    NSURLGenerationIdentifierKey = "NSURLGenerationIdentifierKey",
    NSURLDocumentIdentifierKey = "NSURLDocumentIdentifierKey",
    NSURLAddedToDirectoryDateKey = "NSURLAddedToDirectoryDateKey",
    NSURLQuarantinePropertiesKey = "NSURLQuarantinePropertiesKey",
    NSURLFileIdentifierKey = "NSURLFileIdentifierKey",
    NSURLFileContentIdentifierKey = "NSURLFileContentIdentifierKey",
    NSURLMayShareFileContentKey = "NSURLMayShareFileContentKey",
    NSURLMayHaveExtendedAttributesKey = "NSURLMayHaveExtendedAttributesKey",
    NSURLIsPurgeableKey = "NSURLIsPurgeableKey",
    NSURLIsSparseKey = "NSURLIsSparseKey",
    NSURLThumbnailDictionaryKey = "NSURLThumbnailDictionaryKey",
    NSURLThumbnailKey = "NSURLThumbnailKey",
    NSThumbnail1024x1024SizeKey = "NSThumbnail1024x1024SizeKey",
    NSURLTotalFileAllocatedSizeKey = "NSURLTotalFileAllocatedSizeKey",
    NSURLFileProtectionKey = "NSURLFileProtectionKey",
    NSURLFileProtectionNone = "NSURLFileProtectionNone",
    NSURLFileProtectionComplete = "NSURLFileProtectionComplete",
    NSURLFileProtectionCompleteUnlessOpen = "NSURLFileProtectionCompleteUnlessOpen",
    NSURLFileProtectionCompleteUntilFirstUserAuthentication = "NSURLFileProtectionCompleteUntilFirstUserAuthentication",
    NSURLFileProtectionCompleteWhenUserInactive = "NSURLFileProtectionCompleteWhenUserInactive",
    NSURLDirectoryEntryCountKey = "NSURLDirectoryEntryCountKey",
    NSURLVolumeLocalizedFormatDescriptionKey = "NSURLVolumeLocalizedFormatDescriptionKey",
    NSURLVolumeTotalCapacityKey = "NSURLVolumeTotalCapacityKey",
    NSURLVolumeAvailableCapacityKey = "NSURLVolumeAvailableCapacityKey",
    NSURLVolumeResourceCountKey = "NSURLVolumeResourceCountKey",
    NSURLVolumeSupportsPersistentIDsKey = "NSURLVolumeSupportsPersistentIDsKey",
    NSURLVolumeSupportsSymbolicLinksKey = "NSURLVolumeSupportsSymbolicLinksKey",
    NSURLVolumeSupportsHardLinksKey = "NSURLVolumeSupportsHardLinksKey",
    NSURLVolumeSupportsJournalingKey = "NSURLVolumeSupportsJournalingKey",
    NSURLVolumeIsJournalingKey = "NSURLVolumeIsJournalingKey",
    NSURLVolumeSupportsSparseFilesKey = "NSURLVolumeSupportsSparseFilesKey",
    NSURLVolumeSupportsZeroRunsKey = "NSURLVolumeSupportsZeroRunsKey",
    NSURLVolumeSupportsCaseSensitiveNamesKey = "NSURLVolumeSupportsCaseSensitiveNamesKey",
    NSURLVolumeSupportsCasePreservedNamesKey = "NSURLVolumeSupportsCasePreservedNamesKey",
    NSURLVolumeSupportsRootDirectoryDatesKey = "NSURLVolumeSupportsRootDirectoryDatesKey",
    NSURLVolumeSupportsVolumeSizesKey = "NSURLVolumeSupportsVolumeSizesKey",
    NSURLVolumeSupportsRenamingKey = "NSURLVolumeSupportsRenamingKey",
    NSURLVolumeSupportsAdvisoryFileLockingKey = "NSURLVolumeSupportsAdvisoryFileLockingKey",
    NSURLVolumeSupportsExtendedSecurityKey = "NSURLVolumeSupportsExtendedSecurityKey",
    NSURLVolumeIsBrowsableKey = "NSURLVolumeIsBrowsableKey",
    NSURLVolumeMaximumFileSizeKey = "NSURLVolumeMaximumFileSizeKey",
    NSURLVolumeIsEjectableKey = "NSURLVolumeIsEjectableKey",
    NSURLVolumeIsRemovableKey = "NSURLVolumeIsRemovableKey",
    NSURLVolumeIsInternalKey = "NSURLVolumeIsInternalKey",
    NSURLVolumeIsAutomountedKey = "NSURLVolumeIsAutomountedKey",
    NSURLVolumeIsLocalKey = "NSURLVolumeIsLocalKey",
    NSURLVolumeIsReadOnlyKey = "NSURLVolumeIsReadOnlyKey",
    NSURLVolumeCreationDateKey = "NSURLVolumeCreationDateKey",
    NSURLVolumeURLForRemountingKey = "NSURLVolumeURLForRemountingKey",
    NSURLVolumeUUIDStringKey = "NSURLVolumeUUIDStringKey",
    NSURLVolumeNameKey = "NSURLVolumeNameKey",
    NSURLVolumeLocalizedNameKey = "NSURLVolumeLocalizedNameKey",
    NSURLVolumeIsEncryptedKey = "NSURLVolumeIsEncryptedKey",
    NSURLVolumeIsRootFileSystemKey = "NSURLVolumeIsRootFileSystemKey",
    NSURLVolumeSupportsCompressionKey = "NSURLVolumeSupportsCompressionKey",
    NSURLVolumeSupportsFileCloningKey = "NSURLVolumeSupportsFileCloningKey",
    NSURLVolumeSupportsSwapRenamingKey = "NSURLVolumeSupportsSwapRenamingKey",
    NSURLVolumeSupportsExclusiveRenamingKey = "NSURLVolumeSupportsExclusiveRenamingKey",
    NSURLVolumeSupportsImmutableFilesKey = "NSURLVolumeSupportsImmutableFilesKey",
    NSURLVolumeSupportsAccessPermissionsKey = "NSURLVolumeSupportsAccessPermissionsKey",
    NSURLVolumeSupportsFileProtectionKey = "NSURLVolumeSupportsFileProtectionKey",
    NSURLVolumeAvailableCapacityForImportantUsageKey = "NSURLVolumeAvailableCapacityForImportantUsageKey",
    NSURLVolumeAvailableCapacityForOpportunisticUsageKey = "NSURLVolumeAvailableCapacityForOpportunisticUsageKey",
    NSURLVolumeTypeNameKey = "NSURLVolumeTypeNameKey",
    NSURLVolumeSubtypeKey = "NSURLVolumeSubtypeKey",
    NSURLVolumeMountFromLocationKey = "NSURLVolumeMountFromLocationKey",
    NSURLIsUbiquitousItemKey = "NSURLIsUbiquitousItemKey",
    NSURLUbiquitousItemHasUnresolvedConflictsKey = "NSURLUbiquitousItemHasUnresolvedConflictsKey",
    NSURLUbiquitousItemIsDownloadedKey = "NSURLUbiquitousItemIsDownloadedKey",
    NSURLUbiquitousItemIsDownloadingKey = "NSURLUbiquitousItemIsDownloadingKey",
    NSURLUbiquitousItemIsUploadedKey = "NSURLUbiquitousItemIsUploadedKey",
    NSURLUbiquitousItemIsUploadingKey = "NSURLUbiquitousItemIsUploadingKey",
    NSURLUbiquitousItemPercentDownloadedKey = "NSURLUbiquitousItemPercentDownloadedKey",
    NSURLUbiquitousItemPercentUploadedKey = "NSURLUbiquitousItemPercentUploadedKey",
    NSURLUbiquitousItemDownloadingStatusKey = "NSURLUbiquitousItemDownloadingStatusKey",
    NSURLUbiquitousItemDownloadingErrorKey = "NSURLUbiquitousItemDownloadingErrorKey",
    NSURLUbiquitousItemUploadingErrorKey = "NSURLUbiquitousItemUploadingErrorKey",
    NSURLUbiquitousItemDownloadRequestedKey = "NSURLUbiquitousItemDownloadRequestedKey",
    NSURLUbiquitousItemContainerDisplayNameKey = "NSURLUbiquitousItemContainerDisplayNameKey",
    NSURLUbiquitousItemIsExcludedFromSyncKey = "NSURLUbiquitousItemIsExcludedFromSyncKey",
    NSURLUbiquitousItemIsSharedKey = "NSURLUbiquitousItemIsSharedKey",
    NSURLUbiquitousSharedItemCurrentUserRoleKey = "NSURLUbiquitousSharedItemCurrentUserRoleKey",
    NSURLUbiquitousSharedItemCurrentUserPermissionsKey = "NSURLUbiquitousSharedItemCurrentUserPermissionsKey",
    NSURLUbiquitousSharedItemOwnerNameComponentsKey = "NSURLUbiquitousSharedItemOwnerNameComponentsKey",
    NSURLUbiquitousSharedItemMostRecentEditorNameComponentsKey = "NSURLUbiquitousSharedItemMostRecentEditorNameComponentsKey",
    NSURLUbiquitousItemDownloadingStatusNotDownloaded = "NSURLUbiquitousItemDownloadingStatusNotDownloaded",
    NSURLUbiquitousItemDownloadingStatusDownloaded = "NSURLUbiquitousItemDownloadingStatusDownloaded",
    NSURLUbiquitousItemDownloadingStatusCurrent = "NSURLUbiquitousItemDownloadingStatusCurrent",
    NSURLUbiquitousSharedItemRoleOwner = "NSURLUbiquitousSharedItemRoleOwner",
    NSURLUbiquitousSharedItemRoleParticipant = "NSURLUbiquitousSharedItemRoleParticipant",
    NSURLUbiquitousSharedItemPermissionsReadOnly = "NSURLUbiquitousSharedItemPermissionsReadOnly",
    NSURLUbiquitousSharedItemPermissionsReadWrite = "NSURLUbiquitousSharedItemPermissionsReadWrite",
    NSURLUbiquitousItemSupportedSyncControlsKey = "NSURLUbiquitousItemSupportedSyncControlsKey",
    NSURLUbiquitousItemIsSyncPausedKey = "NSURLUbiquitousItemIsSyncPausedKey",
    // NSUserActivity
    NSUserActivityTypeBrowsingWeb = "NSUserActivityTypeBrowsingWeb",
    // NSUserDefaults
    NSUserDefaultsSizeLimitExceededNotification = "com.apple.CFPreferences.byteCountLimitReached",
    NSUbiquitousUserDefaultsNoCloudAccountNotification = "NSUbiquitousUserDefaultsNoCloudAccountNotification",
    NSUbiquitousUserDefaultsDidChangeAccountsNotification = "NSUbiquitousUserDefaultsDidChangeAccountsNotification",
    NSUbiquitousUserDefaultsCompletedInitialSyncNotification = "NSUbiquitousUserDefaultsCompletedInitialSyncNotification",
    NSWeekDayNameArray = "NSWeekDayNameArray",
    NSShortWeekDayNameArray = "NSShortWeekDayNameArray",
    NSMonthNameArray = "NSMonthNameArray",
    NSShortMonthNameArray = "NSShortMonthNameArray",
    NSTimeFormatString = "NSTimeFormatString",
    NSDateFormatString = "NSDateFormatString",
    NSTimeDateFormatString = "NSTimeDateFormatString",
    NSShortTimeDateFormatString = "NSShortTimeDateFormatString",
    NSCurrencySymbol = "NSCurrencySymbol",
    NSDecimalSeparator = "NSDecimalSeparator",
    NSThousandsSeparator = "NSThousandsSeparator",
    NSDecimalDigits = "NSDecimalDigits",
    NSAMPMDesignation = "NSAMPMDesignation",
    NSHourNameDesignations = "NSHourNameDesignations",
    NSYearMonthWeekDesignations = "NSYearMonthWeekDesignations",
    NSEarlierTimeDesignations = "NSEarlierTimeDesignations",
    NSLaterTimeDesignations = "NSLaterTimeDesignations",
    NSThisDayDesignations = "NSThisDayDesignations",
    NSNextDayDesignations = "NSNextDayDesignations",
    NSNextNextDayDesignations = "NSNextNextDayDesignations",
    NSPriorDayDesignations = "NSPriorDayDesignations",
    NSDateTimeOrdering = "NSDateTimeOrdering",
    NSInternationalCurrencyString = "NSInternationalCurrencyString",
    NSShortDateFormatString = "NSShortDateFormatString",
    NSPositiveCurrencyFormatString = "NSPositiveCurrencyFormatString",
    NSNegativeCurrencyFormatString = "NSNegativeCurrencyFormatString",
}

#[unsafe(no_mangle)]
pub static NSZeroPoint: NSPoint = NSPoint::ZERO;
#[unsafe(no_mangle)]
pub static NSZeroSize: NSSize = NSSize::ZERO;
#[unsafe(no_mangle)]
pub static NSZeroRect: NSRect = NSRect::ZERO;
#[unsafe(no_mangle)]
pub static NSEdgeInsetsZero: NSEdgeInsets = NSEdgeInsets { top: 0.0, left: 0.0, bottom: 0.0, right: 0.0 };

/// Foundation's version on the macOS release Sidestep's behaviour is
/// measured against (26), for programs that compare it with a release's.
#[unsafe(no_mangle)]
pub static NSFoundationVersionNumber: f64 = 5026.6;

#[unsafe(no_mangle)]
pub static NSBundleResourceRequestLoadingPriorityUrgent: f64 = f64::MAX;

/// Seconds from 1970 and from 1904 to the reference date, 2001-01-01.
#[unsafe(no_mangle)]
pub static kCFAbsoluteTimeIntervalSince1970: f64 = 978_307_200.0;
#[unsafe(no_mangle)]
pub static kCFAbsoluteTimeIntervalSince1904: f64 = 3_061_152_000.0;
