[package]
name = "sidestep-foundation"
description = "Foundation classes for Sidestep, written with objc2's define_class!"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[target.'cfg(not(target_vendor = "apple"))'.dependencies]
sidestep-runtime.workspace = true
objc2 = { workspace = true, features = ["gnustep-2-1"] }
block2 = { workspace = true, features = ["gnustep-2-1"] }
objc2-foundation = { workspace = true, features = ["gnustep-2-1", "NSObject", "NSString", "NSThread", "NSZone", "NSDictionary", "NSTimer", "NSDate", "NSNotification", "block2", "NSArray", "NSSet", "NSEnumerator", "NSValue", "NSNull", "NSRange", "NSObjCRuntime", "NSGeometry", "objc2-core-foundation", "NSIndexSet", "NSAttributedString", "NSCharacterSet", "NSScanner", "NSPathUtilities", "NSRegularExpression", "NSTextCheckingResult", "NSRunLoop", "NSOperation", "NSData", "NSURL", "NSError", "NSFileManager", "NSProcessInfo", "NSUUID", "NSBundle", "NSUserDefaults", "NSLock", "NSFormatter", "NSDateFormatter", "NSLocale", "NSTimeZone", "NSInvocation", "NSMethodSignature", "NSOrderedSet", "NSSortDescriptor", "NSHashTable", "NSMapTable", "NSPointerFunctions", "NSPointerArray", "NSCache", "NSAffineTransform", "NSUndoManager", "NSProxy", "NSFileWrapper"] }
# Strings and attributed strings.
memchr = "2.7"
libc = "0.2.177"
icu_normalizer = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_casemap = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_collator = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_properties = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_segmenter = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_locale_core = { version = "2.1", default-features = false }
fancy-regex = "0.16"
objc2-core-foundation = { version = "0.3.2", default-features = false, features = ["std", "objc2", "CFRunLoop", "CFDate", "CFAttributedString", "CFDictionary"] }
plist = { version = "1.10.1", default-features = false }
jiff = { version = "0.2.37", default-features = false, features = ["std", "tz-system", "tzdb-zoneinfo"] }
